export const logo = require('../../assets/logo.png');
export const heroBannerBackground = require('../../assets/hero-banner-background.png');
export const heroBannerAnimated = require('../../assets/hero-banner-animated.png');
export const discoverMore = require('../../assets/discoverMore.jpg');
export const statisticalImage = require('../../assets/statisticalImage.png');
export const loginImage = require('../../assets/login.png');
export const registerImage = require('../../assets/login-test.png');
export const profile = require("../../assets/profile.webp")
export const coverBanner = require("../../assets/coverbanner.png")
export const registerProfile = require("../../assets/profile.png")
// export const javeria = require("../../assets/login.png")
// export const anum = require("../../assets/login.png")
// export const minal = require("../../assets/login.png")
// export const maryam = require("../../assets/login.png")
export const sundas = require("../../assets/sundas.jpg")
 export const bushra = require("../../assets/bushra.jpg")
 export const hadia = require("../../assets/hadia.jpeg")
 export const about3 = require("../../assets/about3.png")
export const about = require("../../assets/about.gif")
export const about1 = require("../../assets/about1.png")
export const template1 = require("../../assets/Template1.png")
export const template2 = require("../../assets/Template2.png")
export const template3 = require("../../assets/Template3.png")
export const cover = require("../../assets/Cover.png")
export const cover2 = require("../../assets/Cover2.png")
export const cover3 = require("../../assets/Cover3.png")
